package com.banyan.lab.sdrs.mapper;

import com.banyan.lab.sdrs.entity.NewsArticle;
import com.banyan.lab.sdrs.dto.ArticleRequest;
import com.banyan.lab.sdrs.dto.ArticleResponse;
import java.util.List;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.ReportingPolicy;

/**
 * Entity ↔ DTO. Generated by MapStruct at compile time, so a field added to one
 * side and not the other is a build failure rather than a silent null —
 * {@code unmappedTargetPolicy=ERROR} is set in {@code build.gradle}.
 *
 * <p>The one deliberate rename is {@code newsType} ↔ {@code category}: the
 * column and the enum say what the value is, the wire name matches
 * {@code Article.category} in the shared TypeScript model.
 */
@Mapper(componentModel = "spring", unmappedSourcePolicy = ReportingPolicy.IGNORE)
public interface NewsMapper {

    @Mapping(target = "category", source = "newsType")
    ArticleResponse toResponse(NewsArticle entity);

    List<ArticleResponse> toResponses(List<NewsArticle> entities);

    @Mapping(target = "newsType", source = "category")
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    NewsArticle toEntity(ArticleRequest request);
}
